name: hadith_nawawi_audio
description: "تطبيق الأربعين النووية بصوت الشيخ أحمد النفيس"

publish_to: "none"

version: 1.0.2+5

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  equatable: 
  flutter_bloc: 
  path_provider:
  responsive_framework: 
  flutter_localizations:
    sdk: flutter
  share_plus:
  just_audio: 
  shared_preferences:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
    - assets/json/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/static/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/Cairo-Black.ttf
          weight: 900
          